// <auto-generated />
using System;
using Holocron.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Holocron.Migrations
{
    [DbContext(typeof(HolocronContext))]
    [Migration("20200525074702_initialcreate")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Holocron.Context.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Career")
                        .HasColumnType("text");

                    b.Property<int?>("CharacteristicsBuyId")
                        .HasColumnType("int");

                    b.Property<int?>("CharacteristicsId")
                        .HasColumnType("int");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<int>("FreeCareerRanks")
                        .HasColumnType("int");

                    b.Property<int>("FreeSpecRanks")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("SkillsBuyId")
                        .HasColumnType("int");

                    b.Property<string>("SkillsCareer")
                        .HasColumnType("text");

                    b.Property<string>("SkillsCareerFree")
                        .HasColumnType("text");

                    b.Property<string>("SkillsSpec")
                        .HasColumnType("text");

                    b.Property<string>("SkillsSpecFree")
                        .HasColumnType("text");

                    b.Property<int>("Soak")
                        .HasColumnType("int");

                    b.Property<string>("Specializations")
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .HasColumnType("text");

                    b.Property<int>("Strain")
                        .HasColumnType("int");

                    b.Property<int>("StrainThreshold")
                        .HasColumnType("int");

                    b.Property<int>("UnusedXp")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Wound")
                        .HasColumnType("int");

                    b.Property<int>("WoundThreshold")
                        .HasColumnType("int");

                    b.Property<int>("Xp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacteristicsBuyId");

                    b.HasIndex("CharacteristicsId");

                    b.HasIndex("SkillsBuyId");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Holocron.Context.CharacterInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterInventory");
                });

            modelBuilder.Entity("Holocron.Context.CharacterShip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterShip");
                });

            modelBuilder.Entity("Holocron.Context.Characteristics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AG")
                        .HasColumnType("int");

                    b.Property<int>("BR")
                        .HasColumnType("int");

                    b.Property<int>("CUN")
                        .HasColumnType("int");

                    b.Property<int>("INT")
                        .HasColumnType("int");

                    b.Property<int>("PR")
                        .HasColumnType("int");

                    b.Property<int>("WIL")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Characteristics");
                });

            modelBuilder.Entity("Holocron.Context.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Holocron.Context.GroupCharacter", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.HasKey("GroupId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("GroupCharacters");
                });

            modelBuilder.Entity("Holocron.Context.GroupInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupInventory");
                });

            modelBuilder.Entity("Holocron.Context.GroupShip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupShip");
                });

            modelBuilder.Entity("Holocron.Context.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("PermissionGroup")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Holocron.Context.Skills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ASTRO")
                        .HasColumnType("int");

                    b.Property<int>("ATHL")
                        .HasColumnType("int");

                    b.Property<int>("BRAWL")
                        .HasColumnType("int");

                    b.Property<int>("CHARM")
                        .HasColumnType("int");

                    b.Property<int>("COERC")
                        .HasColumnType("int");

                    b.Property<int>("COMP")
                        .HasColumnType("int");

                    b.Property<int>("COOL")
                        .HasColumnType("int");

                    b.Property<int>("COORD")
                        .HasColumnType("int");

                    b.Property<int>("CORE")
                        .HasColumnType("int");

                    b.Property<int>("CYBERNETICS")
                        .HasColumnType("int");

                    b.Property<int>("DECEP")
                        .HasColumnType("int");

                    b.Property<int>("DISC")
                        .HasColumnType("int");

                    b.Property<int>("EDU")
                        .HasColumnType("int");

                    b.Property<int>("GUNN")
                        .HasColumnType("int");

                    b.Property<int>("LEAD")
                        .HasColumnType("int");

                    b.Property<int>("LORE")
                        .HasColumnType("int");

                    b.Property<int>("LTSABER")
                        .HasColumnType("int");

                    b.Property<int>("MECH")
                        .HasColumnType("int");

                    b.Property<int>("MED")
                        .HasColumnType("int");

                    b.Property<int>("MELEE")
                        .HasColumnType("int");

                    b.Property<int>("NEG")
                        .HasColumnType("int");

                    b.Property<int>("OUT")
                        .HasColumnType("int");

                    b.Property<int>("PERC")
                        .HasColumnType("int");

                    b.Property<int>("PILOTPL")
                        .HasColumnType("int");

                    b.Property<int>("PILOTSP")
                        .HasColumnType("int");

                    b.Property<int>("RANGHVY")
                        .HasColumnType("int");

                    b.Property<int>("RANGLT")
                        .HasColumnType("int");

                    b.Property<int>("RESIL")
                        .HasColumnType("int");

                    b.Property<int>("SKUL")
                        .HasColumnType("int");

                    b.Property<int>("STEAL")
                        .HasColumnType("int");

                    b.Property<int>("SURV")
                        .HasColumnType("int");

                    b.Property<int>("SW")
                        .HasColumnType("int");

                    b.Property<int>("UND")
                        .HasColumnType("int");

                    b.Property<int>("VIGIL")
                        .HasColumnType("int");

                    b.Property<int>("WARF")
                        .HasColumnType("int");

                    b.Property<int>("XEN")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Holocron.Context.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CurrentAdventureId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("SessionToken")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrentAdventureId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Holocron.Context.Character", b =>
                {
                    b.HasOne("Holocron.Context.Characteristics", "CharacteristicsBuy")
                        .WithMany()
                        .HasForeignKey("CharacteristicsBuyId");

                    b.HasOne("Holocron.Context.Characteristics", "Characteristics")
                        .WithMany()
                        .HasForeignKey("CharacteristicsId");

                    b.HasOne("Holocron.Context.Skills", "SkillsBuy")
                        .WithMany()
                        .HasForeignKey("SkillsBuyId");

                    b.HasOne("Holocron.Context.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Holocron.Context.CharacterInventory", b =>
                {
                    b.HasOne("Holocron.Context.Character", null)
                        .WithMany("Inventory")
                        .HasForeignKey("CharacterId");
                });

            modelBuilder.Entity("Holocron.Context.CharacterShip", b =>
                {
                    b.HasOne("Holocron.Context.Character", null)
                        .WithMany("Ships")
                        .HasForeignKey("CharacterId");
                });

            modelBuilder.Entity("Holocron.Context.GroupCharacter", b =>
                {
                    b.HasOne("Holocron.Context.Character", "Character")
                        .WithMany("GroupCharacters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holocron.Context.Group", "Group")
                        .WithMany("GroupCharacters")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Holocron.Context.GroupInventory", b =>
                {
                    b.HasOne("Holocron.Context.Group", null)
                        .WithMany("Inventory")
                        .HasForeignKey("GroupId");
                });

            modelBuilder.Entity("Holocron.Context.GroupShip", b =>
                {
                    b.HasOne("Holocron.Context.Group", null)
                        .WithMany("Ships")
                        .HasForeignKey("GroupId");
                });

            modelBuilder.Entity("Holocron.Context.Permission", b =>
                {
                    b.HasOne("Holocron.Context.Group", "Group")
                        .WithMany("Permissions")
                        .HasForeignKey("GroupId");

                    b.HasOne("Holocron.Context.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Holocron.Context.User", b =>
                {
                    b.HasOne("Holocron.Context.Group", "CurrentAdventure")
                        .WithMany()
                        .HasForeignKey("CurrentAdventureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
